name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install node_modules
        run: npm install
      - name: build the project
        run: npm run build
      - name: Deploying the Project
        run: npm run deploy
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
